name: 'Input Strings'
description: 'Process strings and make them available to the rest of the workflow'
inputs:
  json-input:
    description: 'JSON formatted data for the strings to process'
    required: true
    default: '[]'
outputs:
  name:
    description: "Name"
    value: ${{ fromJSON("['build-dir': 'some/build/dir', 'other-output': 'other']") }}
runs:
  using: "composite"
  steps:
    - id: examine
      run: echo "${{ toJSON(fromJSON(inputs.json-input)) }}"
      shell: bash
  
