name: Test reusable action

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test

    steps:
    
      - uses: actions/checkout@v3

      - uses: .github/actions/string.yml
        name: Test action
        with:
          json-input: '[ { "build-dir": "${{ github.workspace }}/build", "kind": "path" }, { "name": "Michael" } ]'
         

         
      
